### ISSUE TITLE
Can't resolve mousetrap

### ISSUE THREAD

**Issue by spiffyjr** [BalticCode/ngx-hotkeys#1]
**Describe the bug**
ERROR in ./node_modules/@balticcode/ngx-hotkeys/fesm5/balticcode-ngx-hotkeys.js
Module not found: Error: Can't resolve 'mousetrap'

**To Reproduce**
Install module, angular fails.

**Expected behavior**
It should work. :D

Note: adding mousetrap via `npm install mousetrap --save` fixed my issue but that shouldn't be required. I'm not sure why it's not working as I clearly see it in your package.json.

**Version information (please complete the following information):**
 - Angular 6.x. 
 - ngx-hotkeys 1.0.0

**Comment by bohoffi** [comment]
Yes, you're right. It's an issue with the library's package.json. mousetrap is declared as a `peerDependency` but it should be a `dependency`.
What you meant with seeing it in the package.json is the top level package.json used by the demo application.

I will fix the library's dependency issue today.

**Comment by bohoffi** [comment]
@spiffyjr I've just published v2.0.0 which contained  8481a55 and fixes the dependency issue.

**Comment by spiffyjr** [comment]
Thanks.
