### ISSUE TITLE
update to properly support angular 12,13,14

### ISSUE THREAD

**Issue by fxck** [BalticCode/ngx-hotkeys#13]
ngx-hotkeys is currently considered legacy library

```
Processing legacy "View Engine" libraries:
- @balticcode/ngx-hotkeys [es2015/esm2015] (git+https://github.com/BalticCode/ngx-hotkeys.git)
```

esnest package should be generated instead of esm2015 https://dzone.com/articles/how-to-upgrade-angular-packagesenable-ivy-compiler

**Comment by bohoffi** [comment]
@fxck version `4.0.0` was published
