### ISSUE TITLE
cheatSheet not hiding until mouse press

### ISSUE THREAD

**Issue by KroneCorylus** [BalticCode/ngx-hotkeys#4]
HI, im heaving a problem with the cheatSheet, is not hidding when i press, Esc(cheatSheetCloseEsc: true), or the Shortcut asigned(cheatSheetHotkey) until i click once.

**Comment by bohoffi** [comment]
@KroneCorylus this issue is gone with 67e5b96c9b08c7a717e2eda69e04049690300e4f in version 3.0.0
